sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
env:
  global:
  - secure: IbrybaUaJDiwNh8VodFfTIAdSw2Nl4DGRh2oDIO2vL8SPgGilwxY0go5DWrxAG0aP+YIXFkK+SpblFppQqqxnAoLVYmd7kFSJoOZraNqmcJqUYSzrHrWArmuiGzY8gMgOWTsnbzVVNRldN8tpoSwpQB/+YhCtbYb9eqvw+u5Izk=
  - secure: grvHX6c0ReQwRsuQZferI+uyGsKlubujURKuJB8coNdA9lgZcvf+nmCkNBpSML83hSjQkJUTt8XnucNNgL/1VxUhgy0O/wkTUEmcDAU1b80As8NJkbreJcc3HFASA68wou4HoJsFmJV2cpBYoAJJSX+HyT6mYd6pBh09tPfOeBg=
  matrix:
  - TEST_COMMAND="npm run test:unit"
  - TEST_COMMAND="npm run test:integration"
language: node_js
node_js:
- '6'
- '9'
install:
- npm install
- npm run bootstrap
- npm run build
script:
- test $TRAVIS_NODE_VERSION = 6 && export SKIP_REMOTE_BROWSERS=true
- xvfb-run $TEST_COMMAND
branches:
  only:
  - master
