sudo: required
dist: trusty
language: node_js

env:
  global:
  - secure: IbrybaUaJDiwNh8VodFfTIAdSw2Nl4DGRh2oDIO2vL8SPgGilwxY0go5DWrxAG0aP+YIXFkK+SpblFppQqqxnAoLVYmd7kFSJoOZraNqmcJqUYSzrHrWArmuiGzY8gMgOWTsnbzVVNRldN8tpoSwpQB/+YhCtbYb9eqvw+u5Izk=
  - secure: grvHX6c0ReQwRsuQZferI+uyGsKlubujURKuJB8coNdA9lgZcvf+nmCkNBpSML83hSjQkJUTt8XnucNNgL/1VxUhgy0O/wkTUEmcDAU1b80As8NJkbreJcc3HFASA68wou4HoJsFmJV2cpBYoAJJSX+HyT6mYd6pBh09tPfOeBg=

# By default you get two Travis builds for a PR: one that builds the feature
# branch directly (called "branch"), and another that makes a hypothetical merge
# commit on master (called "PR"). The merge build is what really matters, and we
# don't want to waste resources by also building the branch.
branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.npm"

install:
- npm i -g npm@latest
- npm ci
- npm run bootstrap
- npm run build

script:
- $TEST_COMMAND

matrix:
  include:

  - node_js: '8'
    env:
    - TEST_COMMAND="npm run test:unit"

  - node_js: '10'
    env:
    - TEST_COMMAND="npm run test:unit"

  - node_js: '8'
    addons:
      chrome: stable
      firefox: latest
    env:
    - TEST_COMMAND="xvfb-run npm run test:integration"

  - node_js: '10'
    addons:
      chrome: stable
      firefox: latest
    env:
    - TEST_COMMAND="xvfb-run npm run test:integration"

  - node_js: '10'
    addons:
      sauce_connect: true
    env:
    # We can't run Sauce without credentials. PRs from forks don't get secure
    # environment variables. Only run Sauce if we have those vars. Note this
    # means that community PRs never run on Sauce, even when the builds show
    # all green.
    - WCT_SAUCE=$TRAVIS_SECURE_ENV_VARS
    # We don't need to test the local browsers on this WCT integration test
    # run.  Sauce only.
    - SKIP_LOCAL_BROWSERS=true
    - TEST_REMOTE_BROWSERS="OS X 10.11/safari@9,OS X 10.11/safari@10,macOS 10.13/safari@11,Windows 8.1/internet explorer@11,Windows 10/microsoftedge@14,Windows 10/microsoftedge@42"
    - TEST_COMMAND="xvfb-run npx lerna run test:integration --stream --scope web-component-tester --scope @polymer/esm-amd-loader --concurrency 1"
