sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - TEST_COMMAND=npm test
  - TEST_COMMAND=xvfb-run npm run test:integration

language: node_js
node_js:
  - "6"
  - "node"
install:
- npm install
- npm run bootstrap

script:
  - $TEST_COMMAND
