environment:
  nodejs_version: "9"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@latest
  - npm ci
  - npm install
  - rm packages/*/package-lock.json
  - npm run bootstrap
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm run test:unit:windows
  - npm run test:integration:windows

# Don't actually build.
build: off
