install:
  # a version of '' means "the latest one"
  # ... for some reason.
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#selecting-nodejs-or-iojs-version
  - ps: Install-Product node ''
  - npm install
  - rm packages/*/package-lock.json
  - npm run bootstrap
  - npm run build
  - ls -l packages/polyserve/lib

test_script:
  - node --version
  - npm --version
  - npm run test:unit:windows
  - npm run test:integration:windows

# Don't actually build.
build: off
